language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install nose
script:
  - cd src
  - nosetests
  - cd ..
  - pip install .
  - which keepserver
  - keepserver --help
